version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow_pass
      - POSTGRES_DB=mlflow
    volumes: 
      - mlflow_postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=mlflow
      - MINIO_ROOT_PASSWORD=mlflow_pass
    volumes: 
      - mlflow_minio:/data
    ports:
     - "${MINIO_API_PORT}:9000"
     - "${MINIO_CONSOLE_PORT}:9001"
    command: minio server /data --address ":9000" --console-address ":9001"

  mlflow:
    image: mlflow-server:latest
    depends_on:
      - postgres
      - minio
    environment:
      - BACKEND_URI=postgresql://mlflow:mlflow_pass@postgres:5432/mlflow
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - ARTIFACT_URI=s3://mlflow/
      - AWS_ACCESS_KEY_ID=mlflow
      - AWS_SECRET_ACCESS_KEY=mlflow_pass
    ports:
      - "${MLFLOW_PORT}:5000"

volumes:
  mlflow_postgres:
  mlflow_minio:
